apiVersion: v1
kind: Service
metadata:
  name: tiny-go-service
spec:
  selector:
    app: tiny-go-server
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: tiny-go-svc
